# Server Configuration
server.port=8080
server.servlet.context-path=/

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/pgdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Venky@2135
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

# Jackson Configuration (for JSON handling)
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.fail-on-empty-beans=false

# Logging Configuration
logging.level.com.naiapps.pgbackend=DEBUG
logging.level.org.springframework.web=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Validation Configuration
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false



# Cashfree Configuration
cashfree.appId=TEST108726149193eff801ec3d64612141627801
cashfree.secretKey=cfsk_ma_test_cff4a482bc1bd8075fa0afc4fe4a7b5a_14335055
cashfree.baseUrl=https://sandbox.cashfree.com/pg

# CORS Configuration
cors.allowed-origins=http://localhost:4200

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kondavenky3995@gmail.com
spring.mail.password=phrm pjgv xwqk wyll
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
